import Link from 'next/link'

export const metadata = {
    title: 'Souala Elhoussine — Biography',
    description: 'Full academic and professional biography of Souala Elhoussine',
}

export default function BioPage() {
    return (
        <div className="max-w-3xl mx-auto px-6 py-20">
            <h1 className="text-4xl font-black mb-6">SOUALA ELHOUSSINE — Biography</h1>

            <p className="leading-relaxed mb-4">My name is Souala Elhoussine. I am a Computer Systems Engineer, Software Engineer, and currently a PhD researcher in Quantum Computing. My journey has been driven by a deep passion for mathematics, physics, computer science, and the pursuit of understanding how complex systems work, from classical computing infrastructures to emerging quantum technologies.</p>

            <p className="leading-relaxed mb-4">I began my higher education in 2019 at the Higher School of Computer Science of Sidi Bel Abbès (ESI-SBA), one of Algeria&apos;s leading engineering schools in computer science. From the beginning, I was particularly attracted to mathematics and physics. These subjects were not simply academic requirements for me; they were areas in which I genuinely enjoyed investing time and effort. Throughout my studies, I consistently performed strongly in mathematical and analytical subjects, including algebra, mathematical analysis, probability, statistics, algorithms, and computer architecture. During my first year, I achieved perfect marks in both computer architecture examinations, an achievement that reinforced my interest in understanding computers from both theoretical and engineering perspectives.</p>

            <p className="leading-relaxed mb-4">The first two years at ESI-SBA were heavily focused on scientific and theoretical foundations. We studied mathematics, algorithms, data structures, logic, electronics, physics, probability, statistics, computer architecture, operating systems, and programming fundamentals. These years developed my analytical thinking and provided a rigorous foundation that would later support both my engineering work and research activities. During the second year, I participated in a team project involving the development of an examination planning system using PHP and JavaScript. Working within a team of six students taught me the importance of collaboration, software engineering methodologies, communication, and project organization. Alongside this project, every module included practical assignments, technical reports, Linux administration tasks, networking laboratories, and software development exercises that gradually transformed theoretical knowledge into practical skills.</p>

            <p className="leading-relaxed mb-4">At the end of the preparatory cycle, all students had to pass a competitive national examination in order to access the engineering cycle. The examination served as a major selection process and determined admission into advanced engineering studies. Through consistent preparation and strong academic performance, I successfully ranked among the top ten candidates nationally, allowing me to continue my engineering education.</p>

            <h2 className="text-2xl font-bold mt-8 mb-4">Core Engineering Years</h2>
            <p className="leading-relaxed mb-4">My third year marked a transition toward core computer science disciplines. The curriculum focused on networking, cryptography, databases, operating systems, software engineering, probability, and statistics. During this period, I participated in the development of a platform designed to manage academic projects at ESI-SBA, allowing students and supervisors to track progress and coordinate project activities. This project exposed me to the challenges of designing software systems intended for real organizational needs.</p>

            <p className="leading-relaxed mb-4">In the fourth year, students had to choose among three specializations: Artificial Intelligence, Web Technologies, and Computer Systems Engineering. I selected Computer Systems Engineering (ISI) because it aligned most closely with my interests in systems, networking, cybersecurity, software architecture, and distributed computing. During this year, we studied advanced algorithms, networking, cybersecurity, web development, mobile development, software design, UML modeling, project management, and introductory artificial intelligence. One of the major projects of this year was the development of a complete clinical information system that included infrastructure design, network architecture, security planning, and software modules for managing patients, doctors, appointments, medical records, and administrative operations. This project provided valuable experience in designing and implementing large-scale information systems.</p>

            <p className="leading-relaxed mb-4">The fifth year was divided into two complementary tracks: an engineering graduation project and a research-oriented master&apos;s project. For my master&apos;s research project, I worked on object detection using deep learning for automotive spare parts. The objective was to develop intelligent computer vision models capable of recognizing spare parts automatically from images. This project introduced me to machine learning research methodologies, neural networks, deep learning, and computer vision. For my engineering project, I developed AutoHub, a startup-oriented platform integrating an automotive spare parts marketplace, an AI-powered visual search system for identifying spare parts through image recognition, and an Uber-like towing service that connected vehicle owners with towing operators and mechanics. The platform also included communication and management tools for customers and service providers. This project combined software engineering, artificial intelligence, entrepreneurship, and product design into a single integrated solution.</p>

            <h2 className="text-2xl font-bold mt-8 mb-4">Internships & Research</h2>
            <p className="leading-relaxed mb-4">Alongside my studies, I completed several internships. My first internship was at Sonelgaz during my third year, where I spent one month working on IT infrastructure and technical systems. During my fourth year, I completed a second internship at Sonelgaz lasting two months, gaining additional exposure to enterprise information systems, networking environments, and operational technologies. For my final graduation internship, I joined the Computer Science Research Laboratory of Sidi Bel Abbès (LabRI-SBA) for six months. LabRI-SBA is a recognized research laboratory within ESI-SBA dedicated to advancing computer science research and doctoral education. This internship represented my first significant exposure to scientific research. I became involved in literature reviews, experimentation, academic discussions, and research methodologies. More importantly, this experience fundamentally changed my perception of my future career by introducing me to the world of research and innovation.</p>

            <h2 className="text-2xl font-bold mt-8 mb-4">Professional Experience</h2>
            <p className="leading-relaxed mb-4">After graduating in 2024, I entered the software industry as a Software Engineer at Apollo Digital Solutions. During approximately fourteen months with the company, I worked on modern web applications, cloud deployments, backend systems, APIs, software architecture, CI/CD pipelines, and production-grade platforms. This experience significantly strengthened my engineering skills and exposed me to real-world challenges involving scalability, maintainability, performance, and collaboration within professional development teams. Following this role, I joined SobiAPI as a Backend Engineer, where I focused on backend development, API design, database management, and distributed systems. These professional experiences allowed me to bridge the gap between academic knowledge and industrial software engineering practices.</p>

            <h2 className="text-2xl font-bold mt-8 mb-4">Research Journey</h2>
            <p className="leading-relaxed mb-4">Despite enjoying software engineering, I gradually realized that my long-term ambitions were increasingly oriented toward research. I became fascinated by quantum computing and its potential to transform computation, optimization, cryptography, and information processing. Motivated by this interest, I decided to pursue doctoral studies and participated in the highly competitive national entrance examination for doctoral programs in Quantum Computing. More than 3,000 candidates participated across various specializations and institutions. The examination consisted of two major components: one focused on algorithms and data structures, and a second, higher-coefficient examination covering quantum computing, databases, networking, and cybersecurity. Through extensive preparation and dedication, I ranked first among candidates coming from quantum computing master&apos;s programs and secured admission into the doctoral program. Nationally, only 51 candidates were selected across seven universities, making this one of the most significant achievements of my academic career.</p>

            <p className="leading-relaxed mb-4">Today, I am a PhD researcher in Quantum Computing, working on Quantum-Safe Blockchain and Distributed Ledger Technologies. My research focuses on the intersection of quantum computing, cybersecurity, cryptography, distributed systems, and blockchain technologies. My interests include quantum algorithms, quantum optimization, quantum error correction, fault-tolerant quantum computing, post-quantum cryptography, quantum networking, and secure distributed infrastructures. As part of my doctoral work, I am currently preparing my first scientific publication through an extensive literature review and research investigation related to my thesis topic.</p>

            <p className="leading-relaxed mb-4">To strengthen my expertise in quantum technologies, I have actively pursued additional training beyond formal university education. I successfully completed the Google Quantum AI Coursera certificate &quot;Hands-on Quantum Error Correction with Google Quantum AI,&quot; which deepened my understanding of quantum error correction techniques and fault-tolerant quantum computing. I continue to study quantum algorithms, quantum information theory, and quantum hardware through self-directed learning, research papers, online courses, and practical experimentation using Qiskit and IBM Quantum Cloud platforms. I regularly implement quantum algorithms and explore quantum systems through simulations and cloud-based quantum hardware.</p>

            <p className="leading-relaxed mb-4">I have also participated in several quantum computing hackathons and research-oriented collaborative initiatives. These activities have involved implementing scientific papers, conducting literature reviews, exploring optimization techniques, and applying quantum computing approaches to NP-hard problems. Through these experiences, I have gained valuable exposure to collaborative research environments and practical quantum software development.</p>

            <p className="leading-relaxed mb-4">Outside my academic and professional activities, I enjoy designing and building innovative projects that combine engineering with real-world impact. Among the projects I have developed are a school management system, a forest fire detection device optimized for large-scale deployment and distribution, a marine radio mesh communication network designed to improve resource coordination between maritime and terrestrial operations, various client platforms and dashboards, and a medical image annotation platform inspired by professional systems such as IMAIOS for image labeling and annotation workflows.</p>

            <p className="leading-relaxed mb-4">My journey reflects a progression from strong scientific foundations in mathematics and physics, through rigorous engineering education and professional software development, toward advanced research in quantum computing. Each stage contributed unique skills and perspectives that continue to shape my work today. My long-term goal is to contribute to the advancement of quantum computing, particularly in quantum algorithms, quantum optimization, fault-tolerant architectures, post-quantum cryptography, and secure distributed systems, while leveraging my background in software engineering, mathematics, and computer science research to address some of the most challenging computational problems of the future.</p>

            <div className="pt-8 border-t">
                <Link href="/" className="text-accent font-semibold">← Back to home</Link>
            </div>
        </div>
    )
}
