export const techIcons: Record<string, string> = {
  "PHP": "/images/tech/php.svg",
  "JavaScript": "/images/tech/javascript.svg",
  "HTML5": "/images/tech/html5.svg",
  "CSS3": "/images/tech/css3.svg",
  "C++": "/images/tech/cplusplus.svg",
  "React": "/images/tech/react.svg",
  "React 19": "/images/tech/react.svg",
  "Vue.js": "/images/tech/vuejs.svg",
  "Laravel": "/images/tech/laravel.svg",
  "Laravel API": "/images/tech/laravel.svg",
  "Laravel Reverb": "/images/tech/laravel.svg",
  "FastAPI": "/images/tech/fastapi.svg",
  "NestJS": "/images/tech/nestjs.svg",
  "Next.js": "/images/tech/nextjs.svg",
  "Next.js 16": "/images/tech/nextjs.svg",
  "MySQL": "/images/tech/mysql.svg",
  "PostgreSQL": "/images/tech/postgresql.svg",
  "MongoDB": "/images/tech/mongodb.svg",
  "TensorFlow": "/images/tech/tensorflow.svg",
  "Keras": "/images/tech/keras.svg",
  "Scikit-Learn": "/images/tech/scikitlearn.svg",
  "Pandas": "/images/tech/pandas.svg",
  "NumPy": "/images/tech/numpy.svg",
  "OpenCV": "/images/tech/opencv.svg",
  "CNN": "/images/tech/tensorflow.svg",
  "Google Cloud": "/images/tech/googlecloud.svg",
  "Azure": "/images/tech/azure.svg",
  "Docker": "/images/tech/docker.svg",
  "Docker Compose": "/images/tech/docker.svg",
  "Arduino": "/images/tech/arduino.svg",
  "ESP32": "/images/tech/espressif.svg",
  "IoT": "/images/tech/arduino.svg",
  "LoRaWAN": "/images/tech/arduino.svg",
  "Cisco": "/images/tech/networkx.svg",
  "n8n": "/images/tech/n8n.svg",
  "Apify": "/images/tech/apachespark.svg",
  "REST APIs": "/images/tech/fastapi.svg",
  "Microservices": "/images/tech/docker.svg",
  "WooCommerce API": "/images/tech/woocommerce.svg",
  "Web Application": "/images/tech/html5.svg",
  "Web Platform": "/images/tech/html5.svg",
  "Medical Annotation": "/images/tech/opencv.svg",
  "Automated Scraping": "/images/tech/python.svg",
  "Social Scraping": "/images/tech/python.svg",
  "Data Pipelines": "/images/tech/apachekafka.svg",
  "Frontend Optimization": "/images/tech/react.svg",
  "Notes Management": "/images/tech/markdown.svg",
  "Time Tracking": "/images/tech/clockify.svg",
  "Smart Planning": "/images/tech/trello.svg",
  "Subscription Model": "/images/tech/stripe.svg",
  "Course Management": "/images/tech/moodle.svg",
  "Student Management": "/images/tech/moodle.svg",
  "Software Engineering": "/images/tech/git.svg",
  "AI Development": "/images/tech/tensorflow.svg",
  "Automation": "/images/tech/n8n.svg",
  "Digital Transformation": "/images/tech/azure.svg",
  "Marketplace Platform": "/images/tech/shopify.svg",
  "Delivery Management": "/images/tech/docker.svg",
  "Order Coordination": "/images/tech/jira.svg",
  "Provider Workflows": "/images/tech/jira.svg",
  "Logistics Platform": "/images/tech/docker.svg",
  "Route Matching": "/images/tech/googlemaps.svg",
  "Marketplace Coordination": "/images/tech/shopify.svg",
  "Delivery Optimization": "/images/tech/googlemaps.svg",
  "SaaS Platform": "/images/tech/nextjs.svg",
  "School Management": "/images/tech/moodle.svg",
  "Smart E-Learning": "/images/tech/moodle.svg",
  "Education Technology": "/images/tech/moodle.svg",
  "Admin Workflows": "/images/tech/jira.svg",
  "AWS Cloud": "/images/tech/amazonwebservices.svg",
  "Cloud Solutions": "/images/tech/amazonwebservices.svg",
  "RAG": "/images/tech/openai.svg",
  "PDF Management": "/images/tech/pdf.svg",
  "FilamentPHP":  "/images/tech/filamentphp.svg"
};
