version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    env_file:
      - .env
    ports:
      - 3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.next-app.rule=Host(`portfolio.level-up-org.com`)
      - traefik.http.routers.next-app.entrypoints=websecure
      - traefik.http.routers.next-app.tls.certResolver=letsencrypt
      - traefik.http.services.next-app.loadbalancer.server.port=3000
